# Generated by Django 5.2.11 on 2026-02-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('budget_min', models.PositiveIntegerField(default=0, verbose_name='予算下限')),
                ('budget_max', models.PositiveIntegerField(default=0, verbose_name='予算上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='restaurants.category')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='評価(1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='レビュー本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
            },
        ),
    ]
