# Generated by Django 5.2.11 on 2026-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='画像URL'),
        ),
    ]
