# Generated by Django 5.2.11 on 2026-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, upload_to='restaurants/', verbose_name='店舗画像'),
        ),
    ]
