# Generated by Django 5.2.11 on 2026-02-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_image_url_restaurant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='NAGOYAMESHI', max_length=100, verbose_name='会社名')),
                ('company_description', models.TextField(blank=True, verbose_name='会社概要')),
                ('terms_of_service', models.TextField(blank=True, verbose_name='利用規約')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '基本情報設定',
                'verbose_name_plural': '基本情報設定',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有料会員終了日'),
        ),
        migrations.AddField(
            model_name='member',
            name='paid_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有料会員開始日'),
        ),
        migrations.AddField(
            model_name='member',
            name='plan_status',
            field=models.CharField(choices=[('free', '無料会員'), ('paid', '有料会員')], default='free', max_length=10, verbose_name='会員プラン'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='クーポン名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('discount_text', models.CharField(blank=True, max_length=100, verbose_name='割引内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'クーポン',
                'verbose_name_plural': 'クーポン',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='カードブランド')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='下4桁')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='トークン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='restaurants.member')),
            ],
            options={
                'verbose_name': 'カード情報',
                'verbose_name_plural': 'カード情報',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(verbose_name='予約日時')),
                ('people_count', models.PositiveSmallIntegerField(default=1, verbose_name='人数')),
                ('status', models.CharField(choices=[('active', '予約中'), ('canceled', 'キャンセル')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='取得日時')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='restaurants.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会員クーポン',
                'verbose_name_plural': '会員クーポン',
                'constraints': [models.UniqueConstraint(fields=('user', 'coupon'), name='unique_user_coupon')],
            },
        ),
    ]
