# Generated by Django 5.2.11 on 2026-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_sitesetting_member_full_name_member_paid_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stripe顧客ID'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='StripeサブスクID'),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_subscription_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='Stripeサブスク状態'),
        ),
    ]
