# Generated by Django 5.2.11 on 2026-02-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_member_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_change_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='メール変更申請日時'),
        ),
        migrations.AddField(
            model_name='member',
            name='email_change_token',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='メール変更トークン'),
        ),
        migrations.AddField(
            model_name='member',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='変更申請中メールアドレス'),
        ),
    ]
