# Generated by Django 5.2.11 on 2026-02-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_member_email_change_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name='StripeイベントID')),
                ('event_type', models.CharField(max_length=100, verbose_name='イベント種別')),
                ('status', models.CharField(choices=[('pending', '未処理'), ('processed', '処理済み'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='処理状態')),
                ('last_error', models.TextField(blank=True, verbose_name='最終エラー')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='受信日時')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
            ],
            options={
                'verbose_name': 'StripeWebhookイベント',
                'verbose_name_plural': 'StripeWebhookイベント',
                'ordering': ['-received_at'],
            },
        ),
    ]
