# Generated by Django 5.2.11 on 2026-02-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(blank=True, max_length=120, verbose_name='営業時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
    ]
