# Generated by Django 5.2.11 on 2026-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_business_hours_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開状態'),
        ),
    ]
